[package]
authors.workspace = true
build = "build.rs"
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "concision-transformer"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [ "std" ]

full = [ "approx", "default", "rand", "serde" ]

# ********* [FF] Dependencies *********

alloc = [ "concision-core/alloc", "concision-linear/alloc", "serde?/alloc" ]

approx = [
    "concision-core/approx",
    "concision-linear/approx",
    "dep:approx",
    "ndarray/approx",
]

blas = [ "concision-core/blas", "concision-linear/blas", "ndarray/blas" ]

rand = [ "concision-core/rand", "concision-linear/rand", "num/rand" ]

serde = [
    "concision-core/serde",
    "concision-linear/serde",
    "dep:serde",
    "ndarray/serde-1",
    "num/serde",
]

tracing = [ "concision-core/tracing", "concision-linear/tracing", "dep:tracing" ]

# ********* [FF] Environments *********
std = [
    "concision-core/std",
    "concision-linear/std",
    "ndarray/std",
    "num/std",
    "serde?/std",
    "strum/std",
]

[lib]
bench = false
crate-type = [ "cdylib", "rlib" ]
doctest = true
test = true

[[test]]
name = "attention"
required-features = [ "approx", "rand" ]

[build-dependencies]

[dependencies]
concision-core.workspace = true
ndarray.workspace = true
num.workspace = true
paste.workspace = true
smart-default.workspace = true
strum.workspace = true

approx = { optional = true, workspace = true }
serde = { default-features = false, optional = true, workspace = true }
tracing = { optional = true, workspace = true }

[dependencies.concision-linear]
default-features = false
path = "../linear"
version = "0.1.16"

[dev-dependencies]
lazy_static.workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = [ "--cfg", "docsrs" ]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
