[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "concision-neural"
readme.workspace = true
repository.workspace = true
version.workspace = true


[features]
default = [
    "std",
]

blas = [
    "ndarray/blas",
    "concision-core/blas",
]

std = [
    "concision-core/std",
    "ndarray/std",
    "num/std",
    "strum/std",
]

intel-mkl-system = [
    "blas",
    "ndarray-linalg/intel-mkl-system",
]

intel-mkl-static = [
    "blas",
    "ndarray-linalg/intel-mkl-static",
]

netlib-system = [
    "blas",
    "ndarray-linalg/netlib-system",
]

netlib-static = [
    "blas",
    "ndarray-linalg/netlib-static",
]

openblas-system = [
    "blas",
    "ndarray-linalg/openblas-system",
]

openblas-static = [
    "blas",
    "ndarray-linalg/openblas-static",
]

[lib]
bench = false
crate-type = ["rlib"]
doctest = false
test = true

[build-dependencies]

[dependencies]
concision-core = { features = ["full"], path = "../../core", version = "0.1.12" }

anyhow = "1"
itertools = "0.12"
ndarray = { features = ["serde-1"], version = "0.15" }
ndarray-linalg = "0.16"
ndarray-rand = "0.14"
ndarray-stats = "0.5"
num = { features = ["rand", "serde"], version = "0.4" }
petgraph = { features = ["serde-1"], version = "0.6" }
serde = { features = ["derive"], version = "1" }
serde_json = "1"
smart-default = "0.7"
strum = { features = ["derive"], version = "0.26" }

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
