[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "concision-s4"
readme.workspace = true
repository.workspace = true
version.workspace = true

[features]
default = [
    "blas"
]

blas = [
    "ndarray/blas",
    "concision-core/blas",
    "concision-data/blas",
    "concision-neural/blas",
]

intel-mkl-system = [
    "blas",
    "ndarray-linalg/intel-mkl-system",
]

intel-mkl-static = [
    "blas",
    "ndarray-linalg/intel-mkl-static",
]

netlib-system = [
    "blas",
    "ndarray-linalg/netlib-system",
]

netlib-static = [
    "blas",
    "ndarray-linalg/netlib-static",
]

openblas-system = [
    "blas",
    "ndarray-linalg/openblas-system",
]

openblas-static = [
    "blas",
    "ndarray-linalg/openblas-static",
]



[lib]
bench = true
crate-type = ["rlib"]
doctest = false
test = true

[build-dependencies]

[dependencies]
concision-core = { features = ["rand", "serde"], path = "../../core", version = "0.1.12" }
concision-data = { path = "../../data", version = "0.1.12" }
concision-neural = { path = "../neural" }

anyhow.workspace = true
itertools.workspace = true
lazy_static.workspace = true
ndarray = { features = ["approx", "blas", "serde-1"], version = "0.15" }
ndarray-conv = "0.3"
ndarray-linalg = "0.16"
ndarray-rand.workspace = true
ndarray-stats.workspace = true
ndrustfft = "0.4"
num = { features = ["rand", "serde"], version = "0.4" }
rand = "0.8"
realfft = "3"
rustfft = "6"
serde = { features = ["derive"], version = "1" }
serde_json = "1"
smart-default = "0.7"
strum = { features = ["derive"], version = "0.26" }

[dev-dependencies]
approx.workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]
