[package]
authors.workspace = true
categories.workspace = true
default-run = "concise"
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "concise"
readme.workspace = true
repository.workspace = true
version.workspace = true

[[bin]]
name = "concise"
path = "src/main.rs"

[build-dependencies]

[dependencies]
anyhow.workspace = true
concision = { features = ["full"], path = "../../concision", version = "0.1.12" }
ndarray.workspace = true

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]