[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "concision-linear"
readme.workspace = true
repository.workspace = true
version.workspace = true


[features]
default = []

blas = [
    "ndarray/blas",
    "concision-core/blas",
    "concision-neural/blas",
]

std = [
    
]

[lib]
bench = true
crate-type = ["rlib"]
doctest = false
test = true

[build-dependencies]

[dependencies]
concision-core = { path = "../../core", version = "0.1.12" }
concision-neural = { path = "../../nn/neural", version = "0.1.12" }

anyhow.workspace = true
ndarray = { features = ["serde-1"], version = "0.15" }
ndarray-rand.workspace = true
ndarray-stats.workspace = true
num.workspace = true
serde.workspace = true
serde_json.workspace = true
smart-default.workspace = true
strum.workspace = true

[dev-dependencies]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]

[target.wasm32-unknown-unknown]

[target.wasm32-wasi]

