/*
   Appellation: embed <mod>
   Contrib: FL03 <jo3mccain@icloud.com>
*/
//! # Embedding
//!
//! Natural language processing applications rely heavily on the use of embeddings.
//! Embeddings are generally broken down into two categories: contextual and static.
//! Popular static solutions such as word2vec and GloVe are used to create a static
//! embedding of a word or phrase. Contextual embeddings, on the other hand, are
//! generated by a model that takes into account the context of the word or phrase
//! in question. This module provides a variety of embedding solutions for use in
//! natural language processing applications.
pub use self::{embedding::*, utils::*};

pub(crate) mod embedding;

pub mod context;
pub mod words;

pub trait Embed {

}

pub(crate) mod utils {}
