[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
description = "Concision is a data-science toolkit for building robust, data-centric applications in Rust"
edition = "2021"
keywords = ["derive", "macros"]
license = "MIT"
name = "concision-macros"
readme = "README.md"
repository = "https://github.com/FL03/concision"
version = "0.1.6" # TODO - Update the cargo package version

[features]
default = []

[lib]
proc-macro = true
test = false

[dependencies]
proc-macro2 = "1.0.40"
quote = "1.0.20"
syn = { features = ["full"], version = "1.0.98" }

[build-dependencies]

[dev-dependencies.concision]
path = "../concision"