[package]
authors = ["FL03 <jo3mccain@icloud.com>"]
categories = []
description = "Procedural Macros created for Concision, a complete data-science toolkit written in Rust"
edition = "2021"
homepage = "https://scattered-systems.github.io/concision"
keywords = ["macros"]
license = "MIT"
name = "concision-macros"
repository = "https://github.com/scattered-systems/concision"
version = "0.1.11" # TODO - Update the cargo package version

[lib]
test = false

[dependencies]
proc-macro2 = "1.0.46"
quote = "1.0.21"
syn = { features = ["full"], version = "1.0.101" }

[dev-dependencies.concision]
path = "../concision"