[package]
authors.workspace = true
categories.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "concision-macros"
readme.workspace = true
repository.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]
test = false

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.21"
syn = { features = ["full"], version = "1.0.105" }

[dev-dependencies.concision]
path = "../concision"

[target.wasm32-unknown-unknown]
