name: release

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

on:
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:
    inputs:
      environment:
        default: 'crates-io'
        description: 'Environment to publish to'
        required: true
        type: environment

permissions:
  contents: write
  deployments: read
  discussions: write

jobs:
  crates-io:
    if: github.event.inputs.environment == 'crates-io' || github.event_name == 'repository_dispatch'
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    environment:
      name: crates-io
      url: https://crates.io/crates/${{ github.event.repository.name }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        package:
          - concision-utils
          - concision-core
          - concision-data
          - concision-neural
          - concision-derive
          - concision-macros
          - concision
          # non-sdk packages
          - concision-kan
          - concision-s4
          - concision-transformer
          - concision-ext
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      -
        name: Publish (${{ matrix.package }})
        run: cargo publish --locked --package ${{ matrix.package }}
