name: crates-io

concurrency:
  cancel-in-progress: false
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  push:
    tags: [ v*, "*-nightly" ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

permissions:
  contents: read
  deployments: read
  packages: write

jobs:
  features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - 
        name: rustup
        run: |
          rustup self update
          rustup update
      - 
        name: publish (features)
        run: |
          cargo publish --all-features -v -p concision-math
          cargo publish --all-features -v -p concision-core

          cargo publish --all-features -v -p concision-data
          cargo publish --all-features -v -p concision-derive
          cargo publish --all-features -v -p concision-macros
          cargo publish --all-features -v -p concision-kan
          cargo publish --all-features -v -p concision-gnn
          cargo publish --all-features -v -p concision-linear
          cargo publish --all-features -v -p concision-s4
          cargo publish --all-features -v -p concision-transformers

          cargo publish --all-features -v -p concision
      - 
        name: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-
            ${{ runner.os }}-

