name: crates.io

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

env:
  BASENAME: ${{ github.event.repository.name }}
  CARGO_TERM_COLOR: always

on:
  release:
    types: [ published ]
  repository_dispatch:
    types: [ crates-io ]
  workflow_dispatch:

jobs:
  core:
    name: Publish (core)
    runs-on: ubuntu-latest
    env:
      CARGO_PACKAGE_NAME: ${{ github.event.repository.name }}-core
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ env.CARGO_PACKAGE_NAME }})
        run: cargo publish --all-features -v -p ${{ env.CARGO_PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  features:
    name: Publish (features)
    needs: core
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ data, derive, macros ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.event.repository.name }}-${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}-${{ matrix.features }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  models:
    name: Publish (models)
    needs: features
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features: [ kan, gnn, linear ]
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{ github.event.repository.name }}-${{ matrix.features }})
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }}-${{ matrix.features }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    name: Publish (${{ github.event.repository.name }})
    needs: models
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo publish --all-features -v -p ${{ github.event.repository.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}