name: Publish

concurrency: 
  cancel-in-progress: true
  group: ${{ github.event.repository.name }}

env:
  CARGO_TERM_COLOR: always
  CRATE_BASENAME: ${{ github.event.repository.name }}

on:
  release:
    types: [ created ]
  workflow_dispatch:
    inputs:
      publish:
        default: true
        description: 'Publish'
        required: true
        type: boolean

permissions:
  contents: read
  packages: write
  pull-requests: write
  statuses: write

jobs:
  features:
    name: Publish (features)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ core, derive, macros ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.feature }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{env.PACKAGE_NAME}})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  dependents:
    name: Publish (dependents)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature: [ neural, transformers ]
    env:
      PACKAGE_NAME: ${{ github.event.repository.name }}-${{ matrix.feature }}
    steps:
      - uses: actions/checkout@v4
      - name: Publish (${{env.PACKAGE_NAME}})
        run: cargo publish --all-features -v -p ${{ env.PACKAGE_NAME }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
  publish:
    name: Publish (sdk)
    needs: features
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish (sdk)
        run: cargo publish --all-features -v -p ${{ github.event.repository.name }} --token ${{ secrets.CARGO_REGISTRY_TOKEN }}